name: Run Tests and Publish Allure Report

on:
  push:
    branches: [fw-userAuth]  # Adjust as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust as needed

      - name: Install Dependencies
        run: npm install

      - name: Run Tests with Allure Reporter
        run: |
          npx playwright test --reporter=line,allure-playwright
        continue-on-error: true  # Ensures that subsequent steps run even if tests fail

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
